name: cst2335_final_project
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  floor: ^1.5.0
  encrypted_shared_preferences: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true